### ISSUE TITLE
Difference between Finbert-domain and Finbert-QA

### ISSUE THREAD

**Issue by samjoy** [yuanbit/jina-financial-qa-search#1]
In the retriever system, I understand you are using the Finbert-domain. In the ranker, you are using Finbert-QA. What is the difference between the two? Can we use the Finbert-domain in the the ranker?

**Comment by yuanbit** [comment]
Hi @samjoy, Finbert-domain is `bert-base-uncased` further pre-trained on a large financial corpus by ProsusAI: https://github.com/ProsusAI/finBERT

FinBERT-QA is a model fine-tuned on the FiQA dataset. You can also use Finbert-domain as the ranker, but since FinBERT-QA is already trained on FiQA, the results will be better. Feel free to give it a try though!
